-- wallust template - colors-neovim.lua
-- Auto-generated by wallust - DO NOT EDIT

return {
  background = "#131313",
  foreground = "#CACACA",
  cursor = "#6F6F6F",
  color0 = "#3B3B3B",
  color1 = "#0E0E0E",
  color2 = "#0E0E0E",
  color3 = "#3A3A3A",
  color4 = "#3C3C3C",
  color5 = "#4D4D4D",
  color6 = "#4E4E4E",
  color7 = "#ABABAB",
  color8 = "#787878",
  color9 = "#131313",
  color10 = "#131313",
  color11 = "#4E4E4E",
  color12 = "#4F4F4F",
  color13 = "#666666",
  color14 = "#686868",
  color15 = "#ABABAB",
}
