-- wallust template - colors-neovim.lua
-- Auto-generated by wallust - DO NOT EDIT

return {
  background = "#2E2E2E",
  foreground = "#F4F4F4",
  cursor = "#959595",
  color0 = "#535353",
  color1 = "#232323",
  color2 = "#292929",
  color3 = "#646564",
  color4 = "#929292",
  color5 = "#A7A7A7",
  color6 = "#A7A7A7",
  color7 = "#E7E7E7",
  color8 = "#A1A1A1",
  color9 = "#2F2F2F",
  color10 = "#363636",
  color11 = "#868686",
  color12 = "#C2C2C2",
  color13 = "#DFDFDF",
  color14 = "#DFDFDF",
  color15 = "#E7E7E7",
}
