-- wallust template - colors-neovim.lua
-- Auto-generated by wallust - DO NOT EDIT

return {
  background = "#2E2E2E",
  foreground = "#959595",
  cursor = "#959595",
  color0 = "#2E2E2E",
  color1 = "#959595",
  color2 = "#959595",
  color3 = "#959595",
  color4 = "#959595",
  color5 = "#959595",
  color6 = "#959595",
  color7 = "#959595",
  color8 = "#2E2E2E",
  color9 = "#959595",
  color10 = "#959595",
  color11 = "#959595",
  color12 = "#959595",
  color13 = "#959595",
  color14 = "#959595",
  color15 = "#959595",
}
