# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131313)
$foreground = rgb(CACACA)
$color0 = rgb(3B3B3B)
$color1 = rgb(0E0E0E)
$color2 = rgb(0E0E0E)
$color3 = rgb(3A3A3A)
$color4 = rgb(3C3C3C)
$color5 = rgb(4D4D4D)
$color6 = rgb(4E4E4E)
$color7 = rgb(ABABAB)
$color8 = rgb(787878)
$color9 = rgb(131313)
$color10 = rgb(131313)
$color11 = rgb(4E4E4E)
$color12 = rgb(4F4F4F)
$color13 = rgb(666666)
$color14 = rgb(686868)
$color15 = rgb(ABABAB)
