# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

<<<<<<< HEAD
$background = rgb(2E2E2E)
$foreground = rgb(F4F4F4)
$color0 = rgb(535353)
$color1 = rgb(232323)
$color2 = rgb(292929)
$color3 = rgb(646564)
$color4 = rgb(929292)
$color5 = rgb(A7A7A7)
$color6 = rgb(A7A7A7)
$color7 = rgb(E7E7E7)
$color8 = rgb(A1A1A1)
$color9 = rgb(2F2F2F)
$color10 = rgb(363636)
$color11 = rgb(868686)
$color12 = rgb(C2C2C2)
$color13 = rgb(DFDFDF)
$color14 = rgb(DFDFDF)
$color15 = rgb(E7E7E7)
=======
$background = rgba(131313ff)
$foreground = rgba(CACACAff)
$color0 = rgba(3B3B3Bff)
$color1 = rgba(0E0E0Eff)
$color2 = rgba(0E0E0Eff)
$color3 = rgba(3A3A3Aff)
$color4 = rgba(3C3C3Cff)
$color5 = rgba(4D4D4Dff)
$color6 = rgba(4E4E4Eff)
$color7 = rgba(ABABABff)
$color8 = rgba(787878ff)
$color9 = rgba(131313ff)
$color10 = rgba(131313ff)
$color11 = rgba(4E4E4Eff)
$color12 = rgba(4F4F4Fff)
$color13 = rgba(666666ff)
$color14 = rgba(686868ff)
$color15 = rgba(ABABABff)
>>>>>>> hyprland-monochrome
