# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgba(131313ff)
$foreground = rgba(CACACAff)
$color0 = rgba(3B3B3Bff)
$color1 = rgba(0E0E0Eff)
$color2 = rgba(0E0E0Eff)
$color3 = rgba(3A3A3Aff)
$color4 = rgba(3C3C3Cff)
$color5 = rgba(4D4D4Dff)
$color6 = rgba(4E4E4Eff)
$color7 = rgba(ABABABff)
$color8 = rgba(787878ff)
$color9 = rgba(131313ff)
$color10 = rgba(131313ff)
$color11 = rgba(4E4E4Eff)
$color12 = rgba(4F4F4Fff)
$color13 = rgba(666666ff)
$color14 = rgba(686868ff)
$color15 = rgba(ABABABff)
