# Change your home here
$HOME=/home/k1en

# Variables (must be first)
$UserConfigs = $HOME/.config/hypr/configs
source = $UserConfigs/_variables.conf

# Core settings
source = $UserConfigs/env.conf
env = XDG_CURRENT_DESKTOP,Hyprland
source = $UserConfigs/input.conf
source = $UserConfigs/layouts.conf
source = $UserConfigs/settings.conf

# Appearance
source = $UserConfigs/appearance.conf
source = $UserConfigs/animations.conf

# Rules and binds
source = $UserConfigs/rules.conf
source = $UserConfigs/keybinds.conf

# Startup
source = /home/k1en/.config/hypr/configs/startup.conf

# External tools
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/workspaces.conf
