# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CACACA
background         #131313
cursor             #6F6F6F

active_tab_foreground     #131313
active_tab_background     #CACACA
inactive_tab_foreground   #CACACA
inactive_tab_background   #131313

active_border_color   #CACACA
inactive_border_color #131313
bell_border_color     #0E0E0E

color0      #3B3B3B
color1		#0E0E0E
color2		#0E0E0E
color3		#3A3A3A
color4		#3C3C3C
color5		#4D4D4D
color6		#4E4E4E
color7		#ABABAB
color8		#787878
color9		#131313
color10		#131313
color11		#4E4E4E
color12		#4F4F4F
color13		#666666
color14		#686868
color15		#ABABAB
