# Startup applications
# Wallpaper
exec-once = swww-daemon --format argb
exec-once = sleep 1 && swww img $wallDIR/72GXUW.jpg

# thunar
exec-once = thunar --daemon &
# Portal/dbus environment setup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all && systemctl --user import-environment

# Kill and restart portals with correct environment
exec-once = sleep 1 && killall -q xdg-desktop-portal-hyprland xdg-desktop-portal; sleep 1 && /usr/lib/xdg-desktop-portal-hyprland & sleep 2 && /usr/lib/xdg-desktop-portal &

# Polkit
exec-once = $scriptsDir/Polkit.sh
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
# Apps
exec-once = nm-applet --indicator
exec-once = swaync
exec-once = blueman-applet
exec-once = rog-control-center
exec-once = waybar
exec-once = fcitx5 -d
exec-once = thunderbird --headless

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Idle/Lock
exec-once = hypridle
